name: biobb_wf_amber_md_setup
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_analysis==4.1.0
  - biobb_io==4.1.1
  - biobb_structure_utils==4.1.0
  - biobb_chemistry==4.1.0
  - biobb_amber==4.1.0
  - jupyter
  - gfortran==11.3.0
  - libgfortran5==11.3.0
  - plotly
  - nglview
  - simpletraj
